export const urlRoutesConstants = {
	rawfile: "/rawfile",
	newfile: "/newfile"
	// srci: "/dgndcf/srci",
	// sdk: "/dgndcf/sdk",
	// billingAddress: "/dgndcf/billingAddress",
	// shippingAddress: "/dgndcf/shippingAddress",
	// otpEntry: "/dgndcf/otpEntry",
	// reEnterCard: "/dgndcf/reRnterCard",
	// reviewConfirm: "/dgndcf/reviewConfirm",
	// confirmation: "/dgndcf/confirmation",
	// cardholderVerificationChannel: "/dgndcf/cardholderVerificationChannel",
	// cardholderVerificationOtp: "/dgndcf/cardholderVerificationOtp",
	// merchant: "/dgndcf/merchant",
	// accountLockdown: "/dgndcf/accountLockdown",
	// networkVerification: "/dgndcf/networkVerification",
	// verificationChannel: "/dgndcf/verificationChannel",
	// VerificationChannelOtp: "/dgndcf/verificationChannelOtp",
	// removeCard: "/dgndcf/removeCard",
	// removeShippingAddress: "/dgndcf/removeShippingAddress",
	// accountLocked : "/dgndcf/accountLocked",
	// cannotAddcard: "/dgndcf/cannotAddcard",
	// unlockaccount: "/dgndcf/unlockAccount",
	// provCountExceeded : "/dgndcf/provCountExceeded",
	// tooManyProfiles : "/dgndcf/tooManyProfiles",
	// duplicateCard: "/dgndcf/duplicateCard",
	// existingProfile: "/dgndcf/existingProfile",
	// SomethingWentWrong: "/dgndcf/somethingWentWrong"
};
